version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://161.97.112.112:5000
        VITE_APP_NAME: TNT Travel
    ports:
      - "80:80"
    restart: unless-stopped
